version: '3.3'
services:
  nginx-proxy:
    image: rmts/proxy:latest
    restart: always
    container_name: ngnix_proxy
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - /Users/patrick.thomas/dev/ssl:/etc/nginx/certs:ro
#    environment:
#      - "VIRTUAL_PROTO=https"
#      - "VIRTUAL_PORT=443"

  portainer:
    image: portainer/portainer:latest
    restart: always
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

# Generates a default network for this docker compose named docker_default. Add this network as external network
# to your projects:
#
# nginx-proxy:
#      external:
#        name: docker_default
#
# and reference it in your "app" container:
#
# networks:
#  - scoopdeploynet
#  - nginx-proxy

networks:
  default:
    name: docker_default