version: '2'
services:
  app:
    image: rmts/app:7.2-ubuntu18
    volumes:
      - ./:/var/www/html:cached
      - ~/.ssh:/root/.ssh:cached
      - /tmp
      # to enter via ssh (remote testing)
      # ports:
      #   - "20201:22"
    environment:
      # Activate your queue workers, or customize your own within the project and list it here
      - "QUEUE_WORKER=app-default.conf scoopos-aggregations.conf scoopos-blacklist.conf scoopos-mediaserver-default.conf scoopos-mediaserver-formatgeneration.conf scoopos-mediaserver-validation.conf"
      - "VIRTUAL_HOST=CUSTOMER.lvh.me"
    networks:
      - CUSTOMERnet
      - nginx-proxy

  database:
    image: rmts/database:10.3
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
#    ports:
#      - "33062:3306"
    networks:
      - CUSTOMERnet

  database-testing:
    image: rmts/database:10.3
    environment:
      - "MYSQL_DATABASE=testing"
    networks:
      - CUSTOMERnet

  redis:
    image: redis:5-alpine
    networks:
      - CUSTOMERnet

  webpack:
    image: rmts/webpack:10
    volumes:
      - ./:/home/app:cached
      - /home/app/node_modules
    networks:
      - CUSTOMERnet

  elasticsearch:
    image: elasticsearch:7.5.1
    networks:
      - CUSTOMERnet

  kibana:
    image: kibana:7.5.1
    environment:
      - "VIRTUAL_HOST=kibana.CUSTOMER.lvh.me"
      - "VIRTUAL_PORT=5601"
    networks:
      - CUSTOMERnet
      - nginx-proxy

networks:
  CUSTOMERnet:
    driver: bridge
  nginx-proxy:
    external:
      name: docker_default